FROM hiveos-kernel
RUN apt update &&\
    apt install -y build-essential dkms git &&\
    apt clean

RUN git clone https://git.exozy.me/a/zenpower3.git
WORKDIR /zenpower3 
RUN make TARGET=$(find /usr/lib/modules/ -maxdepth 1 -printf '%P\n' | grep hiveos) 
