version: '3.4'

x-common-args: &default_args
  hive_repo: http://hiveos.local/
  kernel_pkg_path: kernel/hiveos-6.1

services:
  hiveos:
    image: hiveos
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        <<: *default_args
        extra_packages: lm-sensors vim
        user_password: mining1234
        root_password: rootmining1234

  hiveos-kernel:
    image: hiveos-kernel
    build:
      context: .
      dockerfile: Dockerfile-kernel
      args: *default_args

  hiveos-nvidia:
    image: hiveos-nvidia
    build:
      context: .
      dockerfile: Dockerfile-nvidia
      args: *default_args

  hiveos-opencl:
    image: hiveos-opencl
    build:
      context: .
      dockerfile: Dockerfile-opencl
      args:
        <<: *default_args
        opencl_version: 5.4_5.4.6

  kernel-build:
    image: kernel-build
    build:
      context: .
      dockerfile: Dockerfile-kernelbuild
      args:
        <<: *default_args
        kernel_version: 6.7.6
